### ISSUE TITLE
Timeline for our Frontend

### ISSUE THREAD

**Issue by mhalilovic** [awildturtok/hamburg-beer-xml#4]
We need a timeline in our Frontend. 

- Build a timeline that can or is filled with proxy data for our frontend.

**Comment by awildturtok** [comment]
I have started working on a small small implementation, it is functional, but not nice and lacks a lot of nice features.

![image](https://user-images.githubusercontent.com/1553491/27254102-92c989d4-5381-11e7-954d-fe673ace42d4.png)

**Comment by mhalilovic** [comment]
Nice!
![capture1](https://user-images.githubusercontent.com/2799766/28173408-b050d0f8-67ee-11e7-8744-1f27eaa8b32b.PNG)
