### ISSUE TITLE
Short presentation of Progress on Tuesday/Wednesday

### ISSUE THREAD

**Issue by mhalilovic** [awildturtok/hamburg-beer-xml#6]
We have to present our progress in front of the other groups.

- Prepare the presentation
- Do the presentation

**Comment by m273d15** [comment]
For CW 25: Result of issue #2 can be used for demonstration if needed.

**Comment by SkadisRevenge2** [comment]
Here's the link for the presentation this Wednesday:
https://docs.google.com/presentation/d/1GK8r9AQczR-_keEXc13XY6eegkJUl-OtF32QnJFgmKI/edit?usp=sharing
Feel free to change anything I got wrong or that you don't like (or tell me to change it. I won't have Internet access on Tuesday, but I will have on Monday night and Wednesday).

Also, I'm guessing we'll only do a live demo during the final presentation, right?

**Comment by TortugaAttack** [comment]
as far as i understand him, we have to show a live demo also during the milestone. :/
The detail view will be finished so we can show this.

**Comment by mhalilovic** [comment]
No more presentations left. Nice!
