### ISSUE TITLE
Image Crawler for local links in XML file

### ISSUE THREAD

**Issue by mhalilovic** [awildturtok/hamburg-beer-xml#7]
Our XML-Data has links to images that do not work. The images are available online and were uploaded by "Museum für Kunst und Gewerbe" on Wikimedia Commons and can be found by searching them with the image name.

- Write a script that finds missing images online and downloads them.
- Provide a connection between the links in the XML-Data and the downloaded images. (e.g. identical file name)

**Comment by m273d15** [comment]
Does this mean, that the execution of your script also modifies the lido XML file?

**Comment by imnona** [comment]
@m273d15 I think so.
we can check it tommorow together.
I check it one more time manuel and it cover all available images on XML file.

**Comment by m273d15** [comment]
This would be nice. If this assumption holds, we could simply execute your script followed by the xsl transformation and all path problems were solved :+1:

**Comment by m273d15** [comment]
Can we close this issue?
