### ISSUE TITLE
Integrate XML data into basex

### ISSUE THREAD

**Issue by m273d15** [awildturtok/hamburg-beer-xml#8]
If a docker container is created, the image should already contain a baseX with the lido xml data.

**Comment by m273d15** [comment]
Either a script or a Dockerfile-extension ?

**Comment by TortugaAttack** [comment]
done with commit [fc71033](https://github.com/awildturtok/hamburg-beer-xml/commit/fc710335236deffbf50b1855acac522a5abdf9a4)
and commit [7e4c070](https://github.com/awildturtok/hamburg-beer-xml/commit/7e4c070f12638a4ccbc79b6bb76c7add1760c39b)

run `run_docker_container` and the docker container will fetch the `utils/clean.xml` add it to the docker container and after execution will create the database `beer` in the container.
(I added the current clean.xml for simplicity.)
